### ISSUE TITLE
Useful env variables? 

### ISSUE THREAD

**Issue by mr-linch** [bots-house/docker-telegram-bot-api#2]
We can create `docker-entrypoint.sh` where place logic of add optional command line arguments via env, for example:

instead of 

```yaml
command: --http-port=80 --max-connections=3000
```

use env like this:

```yaml
environment:
   HTTP_PORT: 80 
   MAX_CONNECTIONS: 3000
```

What do you think about this feature?
